version: "3.7"
services:
  nginx:
    container_name: nginx
    image: xiaocheng2014/webserver:openresty-1.21.4-1
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ${APP_DIR}/logs/nginx:/opt/bitnami/openresty/nginx/logs:rw
      - ${APP_DIR}/etc/nginx/certs:/opt/bitnami/openresty/nginx/conf/bitnami/certs:ro
      - ${APP_DIR}/etc/nginx/http:/opt/bitnami/openresty/nginx/conf/bitnami/http:ro
      - ${APP_DIR}/etc/nginx/stream:/opt/bitnami/openresty/nginx/conf/bitnami/stream:ro
      - ${APP_DIR}/www:/app/www:rw
    restart: always
  java-web1:
    container_name: java-web1
    image: xiaocheng2014/webserver:openjdk-8u342-jdk
    command: javar -jar /app/app.jar
    #volumes:
    #  - ${APP_DIR}/apps/xxx.jar:/app/app.jar
    network_mode: host
    restart: always
